// import { Inter } from "next/font/google";
import { Poppins, DM_Sans } from "next/font/google";

import "./globals.css";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "900"], // Corrected the weight array
});

const dmSans = DM_Sans ({
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "900"]
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className }>{children}</body>
      {/* <body className={dmSans.className}>{children}</body> */}
    </html>
  );
}
